url: https://christian-trabold.de
description: international travel work food fun blogging

permalink: /:year/:month/:day/:title/
paginate: 10
markdown: kramdown
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

plugins:
  - jekyll-sitemap
  - jemoji
