name: Christian Trabold
url: http://christian-trabold.de
description: international travel work food fun blogging

permalink: /:year/:month/:day/:title/
paginate: 10
markdown: kramdown
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems:
- jekyll-sitemap
- jemoji
